# Project information
site_name: splicer
site_url: https://documentation.splicer.camera/
site_author: Florian Amoser

# Repository
repo_name: splicer
repo_url: https://github.com/florianamoser/splicer
edit_uri: edit/master/documentation
docs_dir: documentation

# Navigation
nav:
  - Abstract: README.md
    # - Acknowledgements: abstract/acknowledgements.md
    # - Print Version: abstract/printversion.md
    # - Licence: abstract/licence.md
    # - Changelog: abstract/changelog.md
  - Introduction: 
    - Research Questions: researchquestions.md 
    - Three Popes and the End of Indexicality: three-popes.md 
    - Working Inside The Apparatus: workinginsidetheapparatus.md 
    - "«Re: Documentation: Splicer»": re-documentation.md
  - Theory:
    - From Window to Hyperobject: theory-1.md
    - From Seduction to Resonance: theory-2.md
    - Grounded Apparatus, Situated Image: theory-3.md
    - Splicer: theory-4.md
    - References: theory-5.md
  - Specifications: 
    - Operational Principles: operationalprinciples.md
    - Physical Dimension: physicaldimensions.md
    - Naming Convention: namingconventions.md
    - Axis Specification: axisspecifications.md
    - Sample Selection Guidelines: samplerequirements.md
    - Image Output: imageoutput.md
    - Light Requirements: lightrequirements.md
    - Relevant Manuals: external-manuals.md
  - Building Splicer:
    - Becoming Splicer: becomingsplicer.md
  #   - Start: placeholder.md
  #   - Lens choice: placeholder.md
  #   - Sensor choice: placeholder.md
  #   - RGB Trichromy filter choice: placeholder.md
  #   - Sourcing Parts: placeholder.md
  #   - Building Aluminium Structure: placeholder.md
  #   - Wiring: placeholder.md
  #   - Gcode Specifications: placeholder.md
  - Initial Startup:
    - Placement and leveling of machine: placeholder.md
  #   - Initial calibration of axis: placeholder.md
  #   - Frame grabber settings: placeholder.md
  #   - Sensor settings and calibration: placeholder.md
  - Using Splicer: 
    - Mounting a Sample: sample-fixtures.md
    - Controlling Splicer: splicer-animator.md
    - Image Capture Software: imagecapture.md
    - Monochrome and RGB Capture: monoandrgb.md
    - Checklists:
      - Setting up for Transport: checklist-transport.md
      - Setting up after Transport: checklist-after-transport.md
      - Before startup: checklist-startup.md
  - Conversations:
    - Methodology: conversation-methodology.md
    - "Conversation 1: Charles Kwong": conversation-1-charleskwong.md
    # - "Conversation 2: Lukas Schmid": placeholder.md
  - Outlook: 
    - Preliminary Summary and Outlook: summaryoutlook.md 
  
    # - Monochrome and tri-color capture: monocolorcapture.md
    # - Merging tri-color capture images: mergingcolorimages.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
# TBD

# Theme
theme:
  name: material
  font:
    text: Space Grotesk
    code: Space Mono
  favicon: assets/favicon.png
  logo: assets/splicer_logo_white.svg
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.footer
    - navigation.top 
    - navigation.path
  palette:
    scheme: default
    primary: black
    accent: red
  extra:
    homepage: https://www.splicer.camera
    
copyright: Copyright &copy; 2025 Florian Amoser

extra_css:
    - templates/pdf-print.css

# Plugins
plugins:
  - search
  - to-pdf:
      author: Florian Amoser
      #copyright: Florian Amoser
      
      cover: true
      back_cover: false
      cover_title: Splicer Manual
      cover_subtitle: Refer to the digital version on documentation.splicer.camera for the latest version.
      cover_logo: assets/splicer_logo_black.svg
      custom_template_path: https://github.com/florianamoser/splicer/tree/main/documentation/templates/

      toc_title: Contents
      heading_shift: false
      toc_level: 3
      ordered_chapter_level: 3
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      render_js: true
      headless_chrome_path: chromium
      #
      output_path: FlorianAmoser_Splicer_Manual.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      debug_html: true
      show_anchors: true
      verbose: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

# Customization
# TBD

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.pathconverter:
      base_path: 'YOUR_REPO_NAME' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
