# Project information
site_name: splicer
site_url: https://florianamoser.github.io/splicer
site_author: Florian Amoser

# Repository
repo_name: splicer
repo_url: https://github.com/florianamoser/splicer
edit_uri: edit/master/documentation
docs_dir: documentation

# Navigation
nav:
  - Abstract: abstract.md
  - Introduction: 
    - About this manual: 
    - About me: 
    - Why splicer:
    - About splicer:
    - How splicer works:
  - Theory:
  - Acknowledgements:
  - Specifications:
    - Naming Convention:
    - Physical Dimension:
    - Axis Specification: axisspecifications.md
    - Image Output:
    - Light needed:
  - Building splicer:
    - Tools:
    - Start:
    - Lens choice:
    - Sensor choice:
    - RGB Trichromy filter choice:
    - Sourcing Parts:
    - Building Aluminium Structure:
    - Wiring:
    - Gcode Specifications:
  - Initial Startup:
    - Placement and leveling of machine:
    - Initial calibration of axis:
    - Frame grabber settings:
    - Sensor settings and calibration:
  - Using Splicer: 
    - Sample Selection Guidelines: samplerequirements.md
    - Controlling Splicer: splicer-animator.md
    - Image Capture Software: imagecapture.md
    - Monochrome and RGB Capture: monoandrgb.md
  - Checklists:
    - Setting up for Transport: checklist-transport.md
    - Setting up after Transport: checklist-after-transport.md
    - Before startup: checklist-startup.md
  - Splicer Conversations:
    - Methodology:
    - Conversation 1 Charles Kwong:
    - Conversation 2 Lukas Schmid:
  
    # - Monochrome and tri-color capture: monocolorcapture.md
    # - Merging tri-color capture images: mergingcolorimages.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
# TBD

# Theme
theme:
  name: material
  font:
    text: Space Grotesk
    code: Space Mono
  # icon:
  #   logo: assets/splicer_logo_white.png
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: red

# Plugins
plugins:
  - search
  - to-pdf:
      author: Florian Amoser
      copyright: Florian Amoser
      
      cover: true
      back_cover: false
      cover_title: splicer owners manual
      cover_subtitle: SUBTITLE TEXT
      custom_template_path: TEMPLATES PATH
      #
      toc_title: TOC TITLE TEXT
      heading_shift: false
      toc_level: 3
      ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      render_js: true
      headless_chrome_path: chromium
      #
      output_path: splicer_manual.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      debug_html: true
      show_anchors: true
      verbose: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

# Customization
# TBD

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
